###################################################
# 
# Group ID (Vulid):  V-38631
# Group Title:  SRG-OS-000032
# Rule ID:  SV-50432r1_rule
# Severity: CAT II
# Rule Version (STIG-ID):  RHEL-06-000148
# Rule Title: The operating system must employ automated mechanisms to facilitate the monitoring and control of remote access methods.
# 
# Vulnerability Discussion:  Ensuring the "auditd" service is active ensures audit records generated by the kernel can be written to disk, or that appropriate actions will be taken if other obstacles exist.
# 
# Check Content:  
# Run the following command to determine the current status of the "auditd" service: 
# 
# # service auditd status
# 
# If the service is enabled, it should return the following: 
# 
# auditd is running...
# 
# If the service is not running, this is a finding.
# 
# Fix Text: The "auditd" service is an essential userspace component of the Linux Auditing System, as it is responsible for writing audit records to disk. The "auditd" service can be enabled with the following command: 
# 
# # chkconfig auditd on   
# 
# CCI: CCI-000067
# 
###################################################

#!/bin/bash


service auditd status